#!/usr/bin/env bash
Lib=$HOME/opt/awk

transpile() { gawk ' {
  print gensub( /\.([^0-9\\*\\$\\+])([a-zA-Z0-9_]*)/, 
    "[\"\\1\\2\"]","g", $0); }'; }

transpiles() {
  for i in *.gold; do 
   if [ $i -nt "$Lib/$i" ]; then
     cat $i | transpile > $Lib/$i
   fi
  done
}
if [ -n "$1" ]; then
  f=$1
  shift
  transpiles
  if [ -t 0 ]
  then       AWKPATH="$Lib:$AWKPATH" gawk -f $Lib/$f $*
  else cat -|AWKPATH="$Lib:$AWKPATH" gawk -f $Lib/$f $*
  fi
else
  mkdir -p $Lib
fi
