#!/usr/bin/env bash
# vim: ft=awk ts=2 sw=2 et :
Src="$HOME/opt/awk"; mkdir -p $Src
code() { cat<<-'EOF' > $Src/axe

BEGIN { 
  THE.some.max = 256 
  THE.ch.skip = "?" 
  THE.stats.cliff = "?" 
  THE.all.rand  = 1
}

@include "lib/gold.awk"
@include "lib/poly.golf"
@include "lib/cols.gold"
@include "lib/sym.gold"
@include "lib/num.gold"
@include "lib/some.gold"
@include "lib/cows.gold"
@include "tests/goldok.gold"

BEGIN { tests(); rogues() }

}
cat $Src/axe | ./gold.awk src=$Src -e '/@include/{transpiles($2)}'
AWKPATH="$Src:$AWKPATH" gawk -f $Src/axe
