#!/usr/bin/env bash
# vim: ft=awk ts=2 sw=2 et :
mkdir -p tmp
gawk -f gold.awk -e'{make($0,"tmp","axe")}'<<EOF
BEGIN { 
  THE.some.max = 256 
  THE.ch.skip = "?" 
  THE.stats.cliff = "?" 
  THE.all.rand  = 1
}

@include "lib/poly.gold"
@include "lib/cols.gold"
@include "lib/sym.gold"
@include "lib/num.gold"
@include "lib/some.gold"
@include "lib/cows.gold"
@include "tests/goldok.gold"

BEGIN { tests(); rogues() }

}
AWKPATH="tmp:$AWKPATH" gawk -f gold.awk -f tmp/axe
