#!/usr/bin/env bash
# build.sh -- assemble single-file `dot` from lib/*.awk.
# Run after editing anything under lib/.

set -e
cd "$(dirname "$0")"

OUT=dot.new

{
cat <<'__HEAD__'
#!/usr/bin/env bash
# dot -- object sugar for gawk. Self-contained.
# Generated by build.sh -- do not edit by hand.
#
# Usage:
#   dot FILE.awk [DATA...]    run rewritten FILE.awk on DATA (or stdin)
#   dot a.awk b.awk DATA      multi-file run; .awk args go through prep
#   cat DATA | dot FILE.awk   stdin works too
#   dot -c FILE.awk           print rewritten source only
#   dot --demo NAME [DATA]    run demos/NAME/*.awk on DATA (or sample.csv, or stdin)
#   dot --demos               list available demos under ./demos/
#   dot --show                dump bundled lib/*.awk (post-prep)
#   dot --help                this message

set -e

# ===== bundled sources (raw, pre-preprocessor) =====================

DOT_PREP=$(cat <<'__PREP__'
__HEAD__

cat lib/prep.awk

cat <<'__MID1__'
__PREP__
)

DOT_RUNTIME=$(cat <<'__RUNTIME__'
__MID1__

# concatenate every .awk in lib/ except prep (prep is its own bash var above).
for f in lib/*.awk; do
  base=$(basename "$f")
  [ "$base" = "prep.awk" ] && continue
  echo "# === $base ==="
  cat "$f"
  echo
done

cat <<'__TAIL__'
__RUNTIME__
)

# =====================================================================
# dispatcher: small named functions, then a clean case on $1.
# read top-down.
# =====================================================================

die()   { echo "dot: $*" >&2; exit 1; }
usage() { awk '/^# Usage:/{p=1} p&&!/^#/{exit} p{sub(/^# ?/,""); print}' "$0"; }

# fresh tempdir for this run; auto-removed on exit.
setup_tmp() {
  TMPD=$(mktemp -d "${TMPDIR:-/tmp}/dot.XXXXXX")
  trap 'rm -rf "$TMPD"' EXIT
}

# preprocess and write, returning the path. two flavours:
#   prep_str NAME  STRING   -- preprocess STRING -> $TMPD/NAME
#   prep_file PATH          -- preprocess file   -> $TMPD/<basename PATH>
prep_str()  { printf '%s\n' "$2" | gawk -e "$DOT_PREP" > "$TMPD/$1"; echo "$TMPD/$1"; }
prep_file() { local b=$(basename "$1"); gawk -e "$DOT_PREP" "$1" > "$TMPD/$b"; echo "$TMPD/$b"; }

# build the gawk -f arg list: bundled runtime, then user .awk files.
build_gawk_args() {
  GAWK_ARGS=( -f "$(prep_str _runtime.awk "$DOT_RUNTIME")" )
  for f; do GAWK_ARGS+=( -f "$(prep_file "$f")" ); done
}

# ----- subcommand: --demos -------------------------------------------
# print one line per demos/NAME/ directory: name + first .awk's first comment.
list_demos() {
  [ -d demos ] || die "no ./demos/ directory in $(pwd)"
  for d in demos/*/; do
    name=$(basename "$d")
    first=$(ls "$d"*.awk 2>/dev/null | head -1)
    desc=""
    [ -n "$first" ] && desc=$(awk 'NR==1 && /^#/ {sub(/^# ?/,""); print; exit}' "$first")
    printf "  %-20s %s\n" "$name" "$desc"
  done
}

# ----- subcommand: --demo NAME [DATA...] -----------------------------
# load every demos/NAME/*.awk; for DATA, prefer explicit args, else
# auto-load demos/NAME/sample.* . pass "-" as the only arg to force stdin.
run_demo() {
  local name=$1; shift
  local dir="demos/$name"
  [ -d "$dir" ] || die "--demo: no such demo: $dir"

  local sources=( "$dir"/*.awk )
  [ -e "${sources[0]}" ] || die "--demo: no .awk files in $dir"

  local data=( "$@" )
  if [ ${#data[@]} -eq 0 ]; then
    local samples=( "$dir"/sample.* )
    [ -e "${samples[0]}" ] && data=( "${samples[0]}" )
  elif [ "${data[0]}" = "-" ]; then
    data=()
  fi

  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

# ----- default mode: dot FILE.awk [DATA...] --------------------------
# split positional args by extension: *.awk -> preprocess + -f; rest -> data.
run_files() {
  local sources=() data=()
  for a; do
    case "$a" in
      *.awk) sources+=( "$a" ) ;;
      *)     data+=( "$a" ) ;;
    esac
  done
  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

# ----- main dispatch -------------------------------------------------

case "${1:-}" in
  ""|-h|--help) usage; exit 0 ;;
  -c)           shift; [ $# -gt 0 ] || die "-c: need FILE.awk"
                exec gawk -e "$DOT_PREP" "$@" ;;
  --show)       setup_tmp; cat "$(prep_str _runtime.awk "$DOT_RUNTIME")"; exit 0 ;;
  --demos)      list_demos; exit 0 ;;
  --demo)       shift; [ $# -gt 0 ] || die "--demo: need NAME (try: --demos)"
                run_demo "$@" ;;
  *)            run_files "$@" ;;
esac
__TAIL__
} > "$OUT"

chmod +x "$OUT"
mv "$OUT" dot
echo "built dot ($(wc -l < dot) lines)"
