#!/usr/bin/env bash
# build.sh -- assemble single-file `dotlearn` from ../dot/lib + ../dotcols/lib + lib/*.
# dotlearn extends dotcols with ML: distance, decision tree, naive Bayes, active learning.

set -e
cd "$(dirname "$0")"

DOT_LIB=../dot/lib
DOTCOLS_LIB=../dotcols/lib
[ -d "$DOT_LIB" ]     || { echo "missing $DOT_LIB" >&2; exit 1; }
[ -d "$DOTCOLS_LIB" ] || { echo "missing $DOTCOLS_LIB" >&2; exit 1; }

OUT=dotlearn.new

{
cat <<'__HEAD__'
#!/usr/bin/env bash
# dotlearn -- ML on top of dotcols. Trees, naive Bayes, active learning.
# Self-contained: bundles dot's runtime + dotcols + ML libs + demos.
# Generated by build.sh -- do not edit by hand.
#
# Usage:
#   dotlearn FILE.awk [DATA...]    run rewritten FILE.awk on DATA (or stdin)
#   dotlearn a.awk b.awk DATA      multi-file run; .awk args go through prep
#   cat DATA | dotlearn FILE.awk   stdin works too
#   dotlearn -c FILE.awk           print rewritten source only
#   dotlearn --demo NAME [DATA]    run demos/NAME/*.awk on DATA
#                                  (auto-prepends demos/NAME/config.csv if present;
#                                   defaults DATA to demos/NAME/sample.*; pass `-` for stdin)
#   dotlearn --demos               list available demos under ./demos/
#   dotlearn --show                dump bundled lib/*.awk (post-prep)
#   dotlearn --get-data            fetch 30 curated CSVs into ./data/
#   dotlearn --help                this message

set -e

# ===== bundled sources (raw, pre-preprocessor) =====================

DOT_PREP=$(cat <<'__PREP__'
__HEAD__

cat "$DOT_LIB/prep.awk"

cat <<'__MID1__'
__PREP__
)

DOT_RUNTIME=$(cat <<'__RUNTIME__'
__MID1__

# Layer 1: dot's runtime
for f in "$DOT_LIB"/*.awk; do
  base=$(basename "$f")
  [ "$base" = "prep.awk" ] && continue
  echo "# === dot/lib/$base ==="
  cat "$f"; echo
done

# Layer 2: dotcols's libs (Num, Sym, Data)
for f in "$DOTCOLS_LIB"/*.awk; do
  echo "# === dotcols/lib/$(basename "$f") ==="
  cat "$f"; echo
done

# Layer 3: dotlearn's own libs
for f in lib/*.awk; do
  echo "# === dotlearn/lib/$(basename "$f") ==="
  cat "$f"; echo
done

cat <<'__TAIL__'
__RUNTIME__
)

# =====================================================================
# dispatcher: small named functions, then a clean case on $1.
# =====================================================================

die()   { echo "dotlearn: $*" >&2; exit 1; }
usage() { awk '/^# Usage:/{p=1} p&&!/^#/{exit} p{sub(/^# ?/,""); print}' "$0"; }

setup_tmp() {
  TMPD=$(mktemp -d "${TMPDIR:-/tmp}/dotlearn.XXXXXX")
  trap 'rm -rf "$TMPD"' EXIT
}

prep_str()  { printf '%s\n' "$2" | gawk -e "$DOT_PREP" > "$TMPD/$1"; echo "$TMPD/$1"; }
prep_file() { local b=$(basename "$1"); gawk -e "$DOT_PREP" "$1" > "$TMPD/$b"; echo "$TMPD/$b"; }

build_gawk_args() {
  GAWK_ARGS=( -f "$(prep_str _runtime.awk "$DOT_RUNTIME")" )
  for f; do GAWK_ARGS+=( -f "$(prep_file "$f")" ); done
}

list_demos() {
  [ -d demos ] || die "no ./demos/ directory in $(pwd)"
  for d in demos/*/; do
    name=$(basename "$d")
    first=$(ls "$d"*.awk 2>/dev/null | head -1)
    desc=""
    [ -n "$first" ] && desc=$(awk 'NR==1 && /^#/ {sub(/^# ?/,""); print; exit}' "$first")
    printf "  %-20s %s\n" "$name" "$desc"
  done
}

# --demo logic: like dot's, plus auto-prepend demos/NAME/config.csv if it exists.
run_demo() {
  local name=$1; shift
  local dir="demos/$name"
  [ -d "$dir" ] || die "--demo: no such demo: $dir"

  local sources=( "$dir"/*.awk )
  [ -e "${sources[0]}" ] || die "--demo: no .awk files in $dir"

  # data list: config.csv (if present) first, then sample.* or user DATA
  local data=()
  [ -f "$dir/config.csv" ] && data+=( "$dir/config.csv" )
  if [ $# -eq 0 ]; then
    local samples=( "$dir"/sample.* )
    [ -e "${samples[0]}" ] && data+=( "${samples[0]}" )
  elif [ "$1" = "-" ]; then
    :   # explicit stdin: leave data at config.csv (or empty)
  else
    data+=( "$@" )
  fi

  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

run_files() {
  local sources=() data=()
  for a; do
    case "$a" in
      *.awk) sources+=( "$a" ) ;;
      *)     data+=( "$a" ) ;;
    esac
  done
  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

# fetch curated CSVs from moot into ./data/{classify,regression,optimize}/
fetch_set() {
  local remote=$1 local_dir=$2 names=$3 BASE="https://raw.githubusercontent.com/timm/moot/master"
  echo "fetching 10 $local_dir -> data/$local_dir/"
  for f in $names; do
    curl -fsSL "$BASE/$remote/$f.csv" -o "data/$local_dir/$f.csv" && echo "  $f"
  done
}
get_data() {
  local CLASSIFY="iris wine glass heart.c diabetes breast.w ionosphere soybean zoo sonar"
  local REGRESS="housing autompg auto93 abalone cpu.act bodyfat machine.cpu cal.housing fishcatch servo"
  local OPTIMIZE="Apache_AllMeasurements HSMGP_num SQL_AllMeasurements rs-6d-c3_obj1 rs-6d-c3_obj2 sol-6d-c2-obj1 SS-A SS-B SS-C SS-D"
  mkdir -p data/classify data/regression data/optimize
  fetch_set classify        classify   "$CLASSIFY"
  fetch_set regression      regression "$REGRESS"
  fetch_set optimize/config optimize   "$OPTIMIZE"
  echo "done. 30 files in ./data/"
}

# ----- main dispatch -------------------------------------------------

case "${1:-}" in
  ""|-h|--help) usage; exit 0 ;;
  -c)           shift; [ $# -gt 0 ] || die "-c: need FILE.awk"
                exec gawk -e "$DOT_PREP" "$@" ;;
  --show)       setup_tmp; cat "$(prep_str _runtime.awk "$DOT_RUNTIME")"; exit 0 ;;
  --demos)      list_demos; exit 0 ;;
  --demo)       shift; [ $# -gt 0 ] || die "--demo: need NAME (try: --demos)"
                run_demo "$@" ;;
  --get-data)   get_data; exit 0 ;;
  *)            run_files "$@" ;;
esac
__TAIL__
} > "$OUT"

chmod +x "$OUT"
mv "$OUT" dotlearn
echo "built dotlearn ($(wc -l < dotlearn) lines)"
