#!/usr/bin/env bash
# build.sh -- assemble single-file `dot2learn` from ../dot2/lib + ../dot2cols/lib + lib/*.

set -e
cd "$(dirname "$0")"

DOT_LIB=../dot2/lib
COLS_LIB=../dot2cols/lib
[ -d "$DOT_LIB" ]  || { echo "missing $DOT_LIB" >&2; exit 1; }
[ -d "$COLS_LIB" ] || { echo "missing $COLS_LIB" >&2; exit 1; }

OUT=dot2learn.new

{
cat <<'__HEAD__'
#!/usr/bin/env bash
# dot2learn -- ML on top of dot2cols (heap-free). Trees, naive Bayes, active learning.
# Self-contained: bundles dot2 runtime + dot2cols + ML libs + demos.
# Generated by build.sh -- do not edit by hand.
#
# Usage:
#   dot2learn FILE.awk [DATA...]    run rewritten FILE.awk on DATA (or stdin)
#   dot2learn a.awk b.awk DATA      multi-file run; .awk args go through prep
#   cat DATA | dot2learn FILE.awk   stdin works too
#   dot2learn -c FILE.awk           print rewritten source only
#   dot2learn --demo NAME [DATA]    run demos/NAME/*.awk on DATA
#                                   (auto-prepends demos/NAME/config.csv if present;
#                                    defaults DATA to demos/NAME/sample.*; pass `-` for stdin)
#   dot2learn --demos               list available demos under ./demos/
#   dot2learn --show                dump bundled lib/*.awk (post-prep)
#   dot2learn --help                this message

set -e

DOT_AWK=$(cat <<'__DOTAWK__'
__HEAD__

cat "$DOT_LIB/dot.awk"

cat <<'__MID1__'
__DOTAWK__
)

DOT_RUNTIME=$(cat <<'__RUNTIME__'
__MID1__

# Layer 1: dot2's runtime
for f in "$DOT_LIB"/*.awk; do
  echo "# === dot2/lib/$(basename "$f") ==="
  cat "$f"; echo
done

# Layer 2: dot2cols
for f in "$COLS_LIB"/*.awk; do
  echo "# === dot2cols/lib/$(basename "$f") ==="
  cat "$f"; echo
done

# Layer 3: dot2learn's own libs
for f in lib/*.awk; do
  echo "# === dot2learn/lib/$(basename "$f") ==="
  cat "$f"; echo
done

cat <<'__TAIL__'
__RUNTIME__
)

die()   { echo "dot2learn: $*" >&2; exit 1; }
usage() { awk '/^# Usage:/{p=1} p&&!/^#/{exit} p{sub(/^# ?/,""); print}' "$0"; }

setup_tmp() {
  TMPD=$(mktemp -d "${TMPDIR:-/tmp}/dot2learn.XXXXXX")
  trap 'rm -rf "$TMPD"' EXIT
}

prep_str()  { printf '%s\n' "$2" | gawk -v PREP=1 -e "$DOT_AWK" > "$TMPD/$1"; echo "$TMPD/$1"; }
prep_file() { local b=$(basename "$1"); gawk -v PREP=1 -e "$DOT_AWK" "$1" > "$TMPD/$b"; echo "$TMPD/$b"; }

build_gawk_args() {
  GAWK_ARGS=( -f "$(prep_str _runtime.awk "$DOT_RUNTIME")" )
  for f; do GAWK_ARGS+=( -f "$(prep_file "$f")" ); done
}

list_demos() {
  [ -d demos ] || die "no ./demos/ directory in $(pwd)"
  for d in demos/*/; do
    name=$(basename "$d")
    first=$(ls "$d"*.awk 2>/dev/null | head -1)
    desc=""
    [ -n "$first" ] && desc=$(awk 'NR==1 && /^#/ {sub(/^# ?/,""); print; exit}' "$first")
    printf "  %-20s %s\n" "$name" "$desc"
  done
}

run_demo() {
  local name=$1; shift
  local dir="demos/$name"
  [ -d "$dir" ] || die "--demo: no such demo: $dir"

  local sources=( "$dir"/*.awk )
  [ -e "${sources[0]}" ] || die "--demo: no .awk files in $dir"

  local data=()
  [ -f "$dir/config.csv" ] && data+=( "$dir/config.csv" )
  if [ $# -eq 0 ]; then
    local samples=( "$dir"/sample.* )
    [ -e "${samples[0]}" ] && data+=( "${samples[0]}" )
  elif [ "$1" = "-" ]; then
    :
  else
    data+=( "$@" )
  fi

  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

run_files() {
  local sources=() data=()
  for a; do
    case "$a" in
      *.awk) sources+=( "$a" ) ;;
      *)     data+=( "$a" ) ;;
    esac
  done
  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

case "${1:-}" in
  ""|-h|--help) usage; exit 0 ;;
  -c)           shift; [ $# -gt 0 ] || die "-c: need FILE.awk"
                exec gawk -v PREP=1 -e "$DOT_AWK" "$@" ;;
  --show)       setup_tmp; cat "$(prep_str _runtime.awk "$DOT_RUNTIME")"; exit 0 ;;
  --demos)      list_demos; exit 0 ;;
  --demo)       shift; [ $# -gt 0 ] || die "--demo: need NAME (try: --demos)"
                run_demo "$@" ;;
  *)            run_files "$@" ;;
esac
__TAIL__
} > "$OUT"

chmod +x "$OUT"
mv "$OUT" dot2learn
echo "built dot2learn ($(wc -l < dot2learn) lines)"
