#!/usr/bin/env bash
# build.sh -- assemble single-file `dotcols` from ../dot/lib/* + lib/*.
# dotcols extends dot with column types (Num, Sym) and a Data table.

set -e
cd "$(dirname "$0")"

DOT_LIB=../dot/lib
[ -d "$DOT_LIB" ] || { echo "missing $DOT_LIB -- check out the awk repo so dot/lib/ exists" >&2; exit 1; }

OUT=dotcols.new

{
cat <<'__HEAD__'
#!/usr/bin/env bash
# dotcols -- column types (Num, Sym) and a Data table for dot.
# Self-contained: bundles dot's runtime + column libs + demos.
# Generated by build.sh -- do not edit by hand.
#
# Usage:
#   dotcols FILE.awk [DATA...]    run rewritten FILE.awk on DATA (or stdin)
#   dotcols a.awk b.awk DATA      multi-file run; .awk args go through prep
#   cat DATA | dotcols FILE.awk   stdin works too
#   dotcols -c FILE.awk           print rewritten source only
#   dotcols --demo NAME [DATA]    run demos/NAME/*.awk on DATA (or sample.csv, or stdin)
#   dotcols --demos               list available demos under ./demos/
#   dotcols --show                dump bundled lib/*.awk (post-prep)
#   dotcols --get-data            fetch 30 curated CSVs into ./data/
#   dotcols --help                this message

set -e

# ===== bundled sources (raw, pre-preprocessor) =====================

DOT_PREP=$(cat <<'__PREP__'
__HEAD__

cat "$DOT_LIB/prep.awk"

cat <<'__MID1__'
__PREP__
)

DOT_RUNTIME=$(cat <<'__RUNTIME__'
__MID1__

# Layer 1: dot's runtime (everything in dot/lib/ except prep)
for f in "$DOT_LIB"/*.awk; do
  base=$(basename "$f")
  [ "$base" = "prep.awk" ] && continue
  echo "# === dot/lib/$base ==="
  cat "$f"
  echo
done

# Layer 2: dotcols's own libs
for f in lib/*.awk; do
  base=$(basename "$f")
  echo "# === dotcols/lib/$base ==="
  cat "$f"
  echo
done

cat <<'__TAIL__'
__RUNTIME__
)

# =====================================================================
# dispatcher: small named functions, then a clean case on $1.
# =====================================================================

die()   { echo "dotcols: $*" >&2; exit 1; }
usage() { awk '/^# Usage:/{p=1} p&&!/^#/{exit} p{sub(/^# ?/,""); print}' "$0"; }

setup_tmp() {
  TMPD=$(mktemp -d "${TMPDIR:-/tmp}/dotcols.XXXXXX")
  trap 'rm -rf "$TMPD"' EXIT
}

prep_str()  { printf '%s\n' "$2" | gawk -e "$DOT_PREP" > "$TMPD/$1"; echo "$TMPD/$1"; }
prep_file() { local b=$(basename "$1"); gawk -e "$DOT_PREP" "$1" > "$TMPD/$b"; echo "$TMPD/$b"; }

build_gawk_args() {
  GAWK_ARGS=( -f "$(prep_str _runtime.awk "$DOT_RUNTIME")" )
  for f; do GAWK_ARGS+=( -f "$(prep_file "$f")" ); done
}

list_demos() {
  [ -d demos ] || die "no ./demos/ directory in $(pwd)"
  for d in demos/*/; do
    name=$(basename "$d")
    first=$(ls "$d"*.awk 2>/dev/null | head -1)
    desc=""
    [ -n "$first" ] && desc=$(awk 'NR==1 && /^#/ {sub(/^# ?/,""); print; exit}' "$first")
    printf "  %-20s %s\n" "$name" "$desc"
  done
}

run_demo() {
  local name=$1; shift
  local dir="demos/$name"
  [ -d "$dir" ] || die "--demo: no such demo: $dir"

  local sources=( "$dir"/*.awk )
  [ -e "${sources[0]}" ] || die "--demo: no .awk files in $dir"

  local data=( "$@" )
  if [ ${#data[@]} -eq 0 ]; then
    local samples=( "$dir"/sample.* )
    [ -e "${samples[0]}" ] && data=( "${samples[0]}" )
  elif [ "${data[0]}" = "-" ]; then
    data=()
  fi

  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

run_files() {
  local sources=() data=()
  for a; do
    case "$a" in
      *.awk) sources+=( "$a" ) ;;
      *)     data+=( "$a" ) ;;
    esac
  done
  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

# fetch curated CSVs from moot into ./data/{classify,regression,optimize}/
get_data() {
  local BASE="https://raw.githubusercontent.com/timm/moot/master"
  local CLASSIFY="iris wine glass heart.c diabetes breast.w ionosphere soybean zoo sonar"
  local REGRESS="housing autompg auto93 abalone cpu.act bodyfat machine.cpu cal.housing fishcatch servo"
  local OPTIMIZE="Apache_AllMeasurements HSMGP_num SQL_AllMeasurements rs-6d-c3_obj1 rs-6d-c3_obj2 sol-6d-c2-obj1 SS-A SS-B SS-C SS-D"
  mkdir -p data/classify data/regression data/optimize
  fetch_set classify        "classify"        "$CLASSIFY"
  fetch_set regression      "regression"      "$REGRESS"
  fetch_set optimize/config "optimize"        "$OPTIMIZE"
  echo "done. 30 files in ./data/"
}
fetch_set() {
  local remote=$1 local_dir=$2 names=$3 BASE="https://raw.githubusercontent.com/timm/moot/master"
  echo "fetching 10 $local_dir -> data/$local_dir/"
  for f in $names; do
    curl -fsSL "$BASE/$remote/$f.csv" -o "data/$local_dir/$f.csv" && echo "  $f"
  done
}

# ----- main dispatch -------------------------------------------------

case "${1:-}" in
  ""|-h|--help) usage; exit 0 ;;
  -c)           shift; [ $# -gt 0 ] || die "-c: need FILE.awk"
                exec gawk -e "$DOT_PREP" "$@" ;;
  --show)       setup_tmp; cat "$(prep_str _runtime.awk "$DOT_RUNTIME")"; exit 0 ;;
  --demos)      list_demos; exit 0 ;;
  --demo)       shift; [ $# -gt 0 ] || die "--demo: need NAME (try: --demos)"
                run_demo "$@" ;;
  --get-data)   get_data; exit 0 ;;
  *)            run_files "$@" ;;
esac
__TAIL__
} > "$OUT"

chmod +x "$OUT"
mv "$OUT" dotcols
echo "built dotcols ($(wc -l < dotcols) lines)"
