#!/usr/bin/env bash
echo $1

for f in *.gold; do
  cat $f | gawk '
    {print gensub(/\.([^0-9\\*\\$\\+])([a-zA-Z0-9_]*)/,"[\"\\1\\2\"]","g", $0)}
  ' > ${f%.*}.awk
done

if [ -f "$1" ]; then
  f=$1
  shift 
  if   [ -t 0 ]
  then         gawk -f ${f%.*}.awk $@
  else cat - | gawk -f ${f%.*}.awk $@
  fi
fi
