#!/usr/bin/env bash
# build.sh -- assemble single-file `dot2` from lib/*.awk.
# dot.awk holds both runtime and preprocessor (gated by PREP=1).

set -e
cd "$(dirname "$0")"

OUT=dot2.new

{
cat <<'__HEAD__'
#!/usr/bin/env bash
# dot2 -- heap-free object sugar for gawk. Self-contained.
# Generated by build.sh -- do not edit by hand.
#
# Usage:
#   dot2 FILE.awk [DATA...]    run rewritten FILE.awk on DATA (or stdin)
#   dot2 a.awk b.awk DATA      multi-file run; .awk args go through prep
#   cat DATA | dot2 FILE.awk   stdin works too
#   dot2 -c FILE.awk           print rewritten source only
#   dot2 --demo NAME [DATA]    run demos/NAME/*.awk on DATA (or sample.*, or stdin)
#   dot2 --demos               list available demos under ./demos/
#   dot2 --show                dump bundled lib/*.awk (post-prep)
#   dot2 --help                this message

set -e

# ===== bundled sources (raw, pre-preprocessor) =====================

DOT_AWK=$(cat <<'__DOTAWK__'
__HEAD__

cat lib/dot.awk

cat <<'__MID1__'
__DOTAWK__
)

DOT_RUNTIME=$(cat <<'__RUNTIME__'
__MID1__

# Concatenate every .awk in lib/. dot.awk is both prep and runtime;
# at runtime, PREP is unset so the prep block doesn't fire.
for f in lib/*.awk; do
  echo "# === $(basename "$f") ==="
  cat "$f"
  echo
done

cat <<'__TAIL__'
__RUNTIME__
)

die()   { echo "dot2: $*" >&2; exit 1; }
usage() { awk '/^# Usage:/{p=1} p&&!/^#/{exit} p{sub(/^# ?/,""); print}' "$0"; }

setup_tmp() {
  TMPD=$(mktemp -d "${TMPDIR:-/tmp}/dot2.XXXXXX")
  trap 'rm -rf "$TMPD"' EXIT
}

# preprocess via dot.awk with -v PREP=1.
prep_str()  { printf '%s\n' "$2" | gawk -v PREP=1 -e "$DOT_AWK" > "$TMPD/$1"; echo "$TMPD/$1"; }
prep_file() { local b=$(basename "$1"); gawk -v PREP=1 -e "$DOT_AWK" "$1" > "$TMPD/$b"; echo "$TMPD/$b"; }

build_gawk_args() {
  GAWK_ARGS=( -f "$(prep_str _runtime.awk "$DOT_RUNTIME")" )
  for f; do GAWK_ARGS+=( -f "$(prep_file "$f")" ); done
}

list_demos() {
  [ -d demos ] || die "no ./demos/ directory in $(pwd)"
  for d in demos/*/; do
    name=$(basename "$d")
    first=$(ls "$d"*.awk 2>/dev/null | head -1)
    desc=""
    [ -n "$first" ] && desc=$(awk 'NR==1 && /^#/ {sub(/^# ?/,""); print; exit}' "$first")
    printf "  %-20s %s\n" "$name" "$desc"
  done
}

run_demo() {
  local name=$1; shift
  local dir="demos/$name"
  [ -d "$dir" ] || die "--demo: no such demo: $dir"

  local sources=( "$dir"/*.awk )
  [ -e "${sources[0]}" ] || die "--demo: no .awk files in $dir"

  local data=( "$@" )
  if [ ${#data[@]} -eq 0 ]; then
    local samples=( "$dir"/sample.* )
    [ -e "${samples[0]}" ] && data=( "${samples[0]}" )
  elif [ "${data[0]}" = "-" ]; then
    data=()
  fi

  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

run_files() {
  local sources=() data=()
  for a; do
    case "$a" in
      *.awk) sources+=( "$a" ) ;;
      *)     data+=( "$a" ) ;;
    esac
  done
  setup_tmp
  build_gawk_args "${sources[@]}"
  exec gawk "${GAWK_ARGS[@]}" "${data[@]}"
}

case "${1:-}" in
  ""|-h|--help) usage; exit 0 ;;
  -c)           shift; [ $# -gt 0 ] || die "-c: need FILE.awk"
                exec gawk -v PREP=1 -e "$DOT_AWK" "$@" ;;
  --show)       setup_tmp; cat "$(prep_str _runtime.awk "$DOT_RUNTIME")"; exit 0 ;;
  --demos)      list_demos; exit 0 ;;
  --demo)       shift; [ $# -gt 0 ] || die "--demo: need NAME (try: --demos)"
                run_demo "$@" ;;
  *)            run_files "$@" ;;
esac
__TAIL__
} > "$OUT"

chmod +x "$OUT"
mv "$OUT" dot2
echo "built dot2 ($(wc -l < dot2) lines)"
